# Use postgres/example user/password credentials

services:
  sudokuell_db:
    image: postgres
    restart: always
    shm_size: 512mb
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
